# seg, prompt (scene), on-screen callout ("" = none)
STYLE = ("Flat 2D vector cartoon illustration in a bright cheerful educational YouTube explainer style, "
         "bold clean dark outlines, saturated warm colors, soft gradient shading, simple rounded characters "
         "with big expressive eyes, detailed background, cinematic composition, 16:9. "
         "Absolutely no text, no letters, no numbers, no logos, no watermarks. Scene: ")
SHOTS = [
 (1, "the inside of a tiny cramped steel sphere submarine cabin, two worried 1960s explorers in sweaters looking out a small round porthole into black water, gauges glowing", ""),
 (1, "a giant ocean pressure crushing a small red car like a soda can, comic exaggeration, deep blue water around it", ""),
 (1, "a gold-and-steel luxury wristwatch with a fluted bezel strapped to the metal hull of a deep sea submarine, bubbles around it, glowing in a spotlight in the dark ocean", ""),
 (1, "a mysterious silhouette of a young man in a 1900s suit standing in front of a giant glowing golden crown shape made of light, dramatic rays, sense of mystery", ""),
 (2, "a small charming Bavarian town in the 1880s with half-timbered houses, a cobblestone street, warm sunset", "1881"),
 (2, "a sad lonely boy of about twelve in old-fashioned clothes holding a small suitcase at a train station, rain, emotional", ""),
 (2, "a smart young man in a 1900s office surrounded by stacks of ledgers and globes, speaking with merchants from many countries, speech bubbles with flags only", ""),
 (2, "two elegant Victorian gentlemen laughing and pointing at a tiny delicate wristwatch on a lady's wrist, while proudly holding big gold pocket watches on chains", ""),
 (2, "a determined young man with a twinkle in his eye holding up a wristwatch to the light like a treasure, sparkles, confident smile", ""),
 (3, "Edwardian London street in 1905 with red brick shops, horse carriages, a small new watch shop opening with ribbon, two young businessmen shaking hands", "1905"),
 (3, "a jeweler in a shop stamping his own mark onto a small watch dial with a tiny hammer while the young watch dealer in the background looks annoyed", ""),
 (3, "a young man at a desk surrounded by hundreds of crumpled paper balls, scratching his head, frustrated, late at night by candlelight", ""),
 (3, "a young man in a bowler hat sitting on top of an open-top horse-drawn double-decker omnibus in London, a friendly blue cartoon genie appearing from a puff of smoke and whispering into his ear", ""),
 (4, "a scientist in a white coat with a magnifying glass inspecting a tiny wristwatch on a big laboratory test bench with thermometers and clocks, 1910", "1910"),
 (4, "a huge old brass ship's marine chronometer in a wooden box glaring at a tiny proud wristwatch, funny rivalry, observatory dome in background", "1914"),
 (4, "an old sailing ship on stormy seas at night, captain using a marine chronometer at the helm", ""),
 (4, "piles of gold coins and tax stamps raining onto a worried shopkeeper during World War One era London, grey tones with red accents", ""),
 (4, "beautiful panoramic view of Geneva Switzerland with Lake Geneva, the tall water fountain jet, snowy Alps, a moving truck full of crates arriving, sunny", "1919"),
 (5, "a cartoon wristwatch with a sad face coughing as water droplets and dust clouds attack it, funny", ""),
 (5, "a cutaway view of a sealed round metal watch case closing tightly like an oyster shell, with a pearl-like glow, technical but cute", "1926"),
 (5, "a determined young woman swimmer in a 1920s swimsuit and cap standing on the white cliffs of Dover at dawn, a small watch on a cord around her neck, grey cold sea", "1927"),
 (5, "a swimmer in rough dark freezing water at night, a support rowing boat with lanterns nearby, waves, cold mist", "10+ HOURS"),
 (5, "a close up of a wristwatch dripping with sea water, still ticking proudly with a gleaming shine, the exhausted swimmer smiling in the background wrapped in a blanket", ""),
 (6, "a newsboy on a 1920s London street waving a giant newspaper, crowds rushing to read it, excitement", ""),
 (6, "a fancy 1920s jewelry shop window with a glass aquarium inside, a gold watch sitting underwater among bubbles and a confused orange goldfish", ""),
 (6, "a crowd of 1920s people of all ages pressing their faces against a shop window in amazement, hats, coats, a small dog", ""),
 (6, "a cutaway diagram of a mechanical watch movement with a half-moon shaped rotor weight spinning, gears glowing gold, motion lines", "1931"),
 (6, "a man happily throwing his old winding key into a trash can while swinging his arm with a wristwatch, comic", ""),
 (7, "a World War Two prisoner of war camp at night with barbed wire fences, wooden huts and sweeping searchlights, moody blue", ""),
 (7, "a stern camp guard taking a wristwatch from a captured young pilot in a leather flight jacket, sad expression", ""),
 (7, "a letter being passed through barbed wire, a hopeful pilot prisoner writing an order by candlelight in a wooden hut", ""),
 (7, "a happy prisoner pilot opening a small package containing a shining wristwatch, other prisoners gathering around smiling, warm light", ""),
 (8, "the summit of Mount Everest with two climbers in 1950s gear raising an arm in triumph, bright blue sky, flags of prayer, snow", "1953"),
 (8, "a scuba diver in the 1950s exploring a bright coral reef with a big dive watch on his wrist, schools of fish, sun rays underwater", ""),
 (8, "a 1950s airline pilot in the cockpit of a propeller airliner over the ocean at sunset, a watch with a two-tone bezel on his wrist, time zones as glowing lines on a globe", ""),
 (8, "important world leaders in suits shaking hands at a grand summit table, each wearing a gold wristwatch, flags of no specific country, camera flashes", ""),
 (8, "a deep sea bathyscaphe submarine rising up from the dark ocean toward the bright surface, a watch on its hull glowing, triumphant", "10,916 m"),
 (9, "an older gentleman in a 1940s suit looking tenderly at a framed photo of his wife on a desk, soft melancholy evening light", ""),
 (9, "a grand stone foundation building in Geneva with columns, a warm glow, a ribbon and a heart symbol above the door", ""),
 (9, "a stock market screen showing an empty search result with a big red X, confused traders in suits shrugging", ""),
 (9, "a glowing molten gold foundry with a crucible pouring liquid gold into molds, sparks, workers in protective gear", ""),
 (10, "a 1960s race track with colorful vintage race cars speeding past a grandstand, a chronograph wristwatch on a driver's wrist in the foreground", "1963"),
 (10, "a dusty shop window display with a lonely chronograph watch and a cobweb, a passerby walking past ignoring it, comic", ""),
 (10, "a handsome 1960s movie star style race car driver with blue eyes and a warm grin leaning on a vintage race car, wearing a chronograph wristwatch", ""),
 (10, "a busy auction house with paddles flying in the air, an auctioneer slamming a gavel, money flying, extreme excitement", "$17.8 MILLION"),
 (10, "a montage collage of a submarine, a swimmer, a mountain summit, a genie on a bus and an auction gavel arranged around a glowing golden wristwatch in the center, celebratory", ""),
]
